#This configuration file is used to override the use of the value.yaml variable.
#Currently, only the configuration with ingressName as nginx is provided.
#If it is another gateway such as istio or treafik, please modify the corresponding gateway requirements
image:
  repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-api
  pullPolicy: Always
  tag: "latest"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: openim.server.com # your hostname
      paths:
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: webapitls  #your hostname tls
      hosts:
        - openim.server.com

openim-msggateway:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-msggateway
    tag: "latest"
    pullPolicy: Always
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: openim.server.com # your hostname
        paths:
          - path: /msg_gateway(/|$)(.*)
            pathType: ImplementationSpecific
    tls:
      - secretName: webapitls  #your hostname tls
        hosts:
          - openim.server.com

# openim-msgtransfer in openim/openim-server/values.yaml not defined, Pass to openim/openim-server/openim-msgtransfer/values.yaml
openim-msgtransfer:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-msgtransfer
    tag: "latest"
    pullPolicy: Always
openim-push:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-push
    tag: "latest"
    pullPolicy: Always
openim-rpc-auth:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-rpc-auth
    tag: "latest"
    pullPolicy: Always
openim-rpc-conversation:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-rpc-conversation
    tag: "latest"
    pullPolicy: Always
openim-rpc-friend:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-rpc-friend
    tag: "latest"
    pullPolicy: Always
openim-rpc-group:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-rpc-group
    tag: "latest"
    pullPolicy: Always
openim-rpc-msg:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-rpc-msg
    tag: "latest"
    pullPolicy: Always
openim-rpc-third:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-rpc-third
    tag: "latest"
    pullPolicy: Always
openim-rpc-user:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-rpc-user
    tag: "latest"
    pullPolicy: Always
