
additionalPrometheusRulesMap:
  redis-mongodb-crash:
    groups:
      - name: database_insert_failure_alerts
        rules:
          - alert: DatabaseInsertFailed
            expr: (increase(MsgInsertRedisFailedCounter{job="openimserver-openim-transfer"}[5m]) > 0) or (increase(MsgInsertMongoFailedCounter{job="openimserver-openim-transfer"}[5m]) > 0)
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Increase in MsgInsertRedisFailedCounter or MsgInsertMongoFailedCounter detected"
              description: "Either MsgInsertRedisFailedCounter or MsgInsertMongoFailedCounter has increased in the last 5 minutes, indicating failures in message insert operations to Redis or MongoDB,maybe the redis or mongodb is crash."

alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_from: 'openimalert@163.com'
      smtp_smarthost: 'smtp.163.com:465'
      smtp_auth_username: 'openimalert@163.com'
      smtp_auth_password: 'YOURAUTHCODE'
      smtp_require_tls: false
      smtp_hello: 'openim-server监控告警'
    route:
      group_by: [ 'alertname' ]
      group_wait: 5s
      group_interval: 5s
      repeat_interval: 1h
      receiver: 'email'
    receivers:
      - name: 'email'
        email_configs:
          - to: '23937403@qq.com'
            headers: { Subject: "[WARN]告警" }
            html: '{{ template "email1" . }}'
            send_resolved: true
  templateFiles:
    template_1.tmpl: |-
        {{ define "email1" }}
        {{ range .Alerts }}
           -------------------------------<br>
           告警程序: prometheus_alert<br>
           告警级别: {{ .Labels.severity }} 级<br>
           告警类型: {{ .Labels.alertname }}<br>
           故障主机: {{ .Labels.instance }}<br>
           故障服务: {{ .Labels.job }}<br>
           告警主题: {{ .Annotations.summary }}<br>
           触发时间: {{ .StartsAt.Format "2020-01-02 15:04:05"}} <br>
           ---------------------------------<br>
        {{ end }}
        {{ end }}
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: { }
    labels: { }
    hosts:
      - openim4.server.top
    paths:
      - /
    tls:
      - secretName: openim4tls
        hosts:
          - openim4.server.top

grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - openim2.server.top
    path: /
    tls:
      - secretName: openim2tls
        hosts:
          - openim2.server.top

prometheus:
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - openim3.server.top
    paths:
      - /
    tls:
      - secretName: openim3tls
        hosts:
          - openim3.server.top